# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: SCH的博客
subtitle: ''
description: 'SCH的博客'
keywords:
author: "SCH"
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://xcgzs.cn/
permalink: article/:abbrlink/ #:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: matery

plugins:
  - hexo-footnotes

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

search:
  path: search.xml
  field: post

permalink_pinyin:
  enable: true
  separator: "-"

githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

neat_enable: true  #打开总开关
neat_html:      
  enable: true      #打开压缩html文件开关
  exclude:          #html的排除列表

neat_css:          
  enable: true      #配置CSS文件开关
  exclude:
    - '**.min.css'   #配置排除文件  

neat_js:
  enable: true       #js压缩开关
  mangle: true       #是否破坏文件名
  output:            #是否输出log日志，默认为true
  compress:
  exclude:
    - '*.min.js'     #js文件压缩排除列表

# hexo-hide-posts
hide_posts:
  enable: true
  # Change the filter name to fit your need
  filter: hidden
  # Generators which you want to expose all posts (include hidden ones) to.
  # Common generators: index, tag, category, archive, sitemap, feed, etc.
  public_generators: []
  # Add "noindex" meta tag to prevent hidden posts from being indexed by search engines
  noindex: true


# PWA
pwa:
  manifest:
    path: /manifest.json
    body:
      name: SCH的博客
      short_name: SCH
      icons:
        - src: /img/logo.jpg
          sizes: 192x192
          type: image/png
        - src: /img/logo.jpg
          sizes: 512x512
          type: image/png
      start_url: /index.html
      theme_color: '#ffffff'
      background_color: '#ffffff'
      display: standalone
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
  priority: 5

# enable: 开启/关闭 推送
# cron: 执行时间周期
# count: 每次提交最新的10篇文章
# date: 更新时间(updated)|创建日期(created)
# https://github.com/lete114/hexo-seo-autopush.git
hexo_seo_autopush:
  cron: 0 4 * * *
  baidu:
    enable: true
    date: created 
    count: 10
  bing:
    enable: true
    date: created 
    count: 10
  google:
    enable: true
    date: created 
    count: 10
    google_file: google_service_account.json # 谷歌服务账户

note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: true #false时PC端不显示图标，但移动端仍会显示，故需要在标签语句中手动no-icon进行标注
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0